apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - image: https://registry.hub.docker.com/v2/repositories/andrebgomes/simple-api
        name: simple-api
        ports:
        - containerPort: 80